import fs from 'fs';
import path from 'path';

const migrationsDir = path.join(process.cwd(), 'drizzle');

if (!fs.existsSync(migrationsDir)) {
  console.log('No migrations directory found, skipping patch.');
  process.exit(0);
}

const files = fs.readdirSync(migrationsDir).filter(f => f.endsWith('.sql'));

for (const file of files) {
  const filePath = path.join(migrationsDir, file);
  let content = fs.readFileSync(filePath, 'utf8');

  // Look for the creation of the audit_logs table generated by Drizzle
  // Example: CREATE TABLE "audit_logs" ( ... );
  const regex = /CREATE TABLE (?:IF NOT EXISTS )?"audit_logs" \([\s\S]*?\)\s*;/g;

  let patchedFile = false;

  content = content.replace(regex, (match) => {
    if (match.includes('PARTITION BY RANGE')) {
      return match; // Already patched
    }
    
    // Replace the trailing semicolon with the partition definition and default partition
    const patched = match.replace(/;\s*$/, '') + 
` PARTITION BY RANGE ("created_at");

CREATE TABLE IF NOT EXISTS "audit_logs_default" PARTITION OF "audit_logs" DEFAULT;`;
    
    console.log(`✅ Patched audit_logs table creation in ${file} to be partitioned.`);
    patchedFile = true;
    return patched;
  });

  // NOTE: RLS policies are now declared in the Drizzle schema via pgPolicy() + .enableRLS()
  // and are automatically included in the generated SQL by drizzle-kit.
  // The old dynamic RLS injection has been removed.

  if (patchedFile) {
    fs.writeFileSync(filePath, content, 'utf8');
  }
}
