/**
 * generate-branding-fallback.ts
 * 
 * Generates `frontend/public/branding-fallback.js` automatically from:
 *   - packages/schema/src/utils/theme-presets.ts (THEME_PRESETS)
 *   - packages/schema/src/utils/color.ts (getContrastColor logic)
 * 
 * This eliminates the manual duplication that could lead to FOUC bugs.
 * Run: bun run scripts/generate-branding-fallback.ts
 */

import { THEME_PRESETS } from '../packages/schema/src/utils/theme-presets';
import path from 'path';

const presetsJson = JSON.stringify(THEME_PRESETS, null, 6)
  // Convert JSON to JS object literal (remove quotes from keys that are valid identifiers)
  .replace(/"(bgLight|bgDark|surfaceLight|surfaceDark|cardLight|cardDark|cardAltLight|cardAltDark|borderLight|borderDark)":/g, '$1:');

const output = `// AUTO-GENERATED by scripts/generate-branding-fallback.ts — DO NOT EDIT MANUALLY.
// Source of truth: packages/schema/src/utils/theme-presets.ts + color.ts
// Purpose: Apply cached tenant branding instantly to prevent FOUC (Flash of Unstyled Content).
// This script runs BEFORE Vite/SolidJS loads, so it uses vanilla JS only.
(function() {
  if (document.getElementById('tenant-branding')) return;

  var host = window.location.hostname;
  var slug = null;
  var ipRegex = /^[0-9.]+$/;

  if (ipRegex.test(host) || host === 'localhost' || host === '127.0.0.1') {
    var params = new URLSearchParams(window.location.search);
    slug = params.get('slug');
  } else {
    var parts = host.split('.');
    if (host.includes('zelys.app')) {
      if (parts.length > 2 && parts[0] !== 'api' && parts[0] !== 'in' && parts[0] !== 'www') {
        slug = parts[0];
      }
    } else if (parts.length > 1 && parts[parts.length - 1] === 'localhost') {
      slug = parts[0];
    } else if (parts.length > 2) {
      slug = parts[0];
    }
  }

  if (!slug) return;

  try {
    var cached = localStorage.getItem('branding:' + slug);
    if (!cached) return;

    var company = JSON.parse(cached);
    var style = document.createElement('style');
    style.id = 'tenant-branding';

    // Generated from packages/schema/src/utils/theme-presets.ts
    var themePresets = ${presetsJson};

    var theme = themePresets[company.themeColor] || themePresets['#64748b'];

    // Generated from packages/schema/src/utils/color.ts — getContrastColor (WCAG 2.0)
    var getContrastColor = function(hex) {
      var cleanHex = hex.replace('#', '');
      if (cleanHex.length === 3 || cleanHex.length === 4) {
        cleanHex = cleanHex.split('').map(function(c) { return c + c; }).join('');
      }
      if (cleanHex.length !== 6 && cleanHex.length !== 8) return '#ffffff';
      var r = parseInt(cleanHex.substring(0, 2), 16);
      var g = parseInt(cleanHex.substring(2, 4), 16);
      var b = parseInt(cleanHex.substring(4, 6), 16);
      if (isNaN(r) || isNaN(g) || isNaN(b)) return '#ffffff';
      var toLinear = function(c) {
        var s = c / 255;
        return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
      };
      var l = 0.2126 * toLinear(r) + 0.7152 * toLinear(g) + 0.0722 * toLinear(b);
      return l > 0.179 ? '#0f172a' : '#ffffff';
    };

    style.textContent =
      ':root {' +
      '--primary: ' + company.primaryColor + ';' +
      '--on-primary: ' + getContrastColor(company.primaryColor) + ';' +
      '--secondary: ' + company.themeColor + ';' +
      '--on-secondary: ' + getContrastColor(company.themeColor) + ';' +
      '--bg-light-val: ' + theme.bgLight + ';' +
      '--bg-dark-val: ' + theme.bgDark + ';' +
      '--surface-light-val: ' + theme.surfaceLight + ';' +
      '--surface-dark-val: ' + theme.surfaceDark + ';' +
      '--card-light-val: ' + theme.cardLight + ';' +
      '--card-dark-val: ' + theme.cardDark + ';' +
      '--card-alt-light-val: ' + theme.cardAltLight + ';' +
      '--card-alt-dark-val: ' + theme.cardAltDark + ';' +
      '--border-light-val: ' + theme.borderLight + ';' +
      '--border-dark-val: ' + theme.borderDark + ';' +
      '}';

    document.head.appendChild(style);
    document.title = (company.tradeName || company.businessName) + ' - Iniciar Sesión';

    // Apply cached favicon to prevent flash of default favicon
    if (company.logoUrl) {
      var link = document.querySelector("link[rel*='icon']");
      if (link) {
        link.href = company.logoUrl;
      } else {
        link = document.createElement('link');
        link.rel = 'shortcut icon';
        link.href = company.logoUrl;
        document.head.appendChild(link);
      }
    }
  } catch(e) {
    console.error('Error in branding fallback:', e);
  }
})();
`;

const outputPath = path.resolve(import.meta.dir, '../frontend/public/branding-fallback.js');
await Bun.write(outputPath, output);
console.log('✅ Generated branding-fallback.js from schema sources');
